### ISSUE TITLE
Token address will be updated first after refunded

### ISSUE THREAD

**Issue by vincent0426** [exo-digital-labs/ERC721R#20]
### testing case "Freely minted NFTs cannot be refunded" and "NFT cannot be refunded twice" have err.
**Freely minted NFTs cannot be refunded**
The first one is because the tokenId should be 2, which is the third token minted in the case. [0, 1] in the previous public tests so the owner minted here should be 2 instead of 1.
**NFT cannot be refunded twice**
The refunded token owner will be updated to the refundAddress, so the second time we call refund, it should be reverted with not token owner first instead of Already refunded.

I'm not sure if only I have encountered the problem.

**Comment by elie222** [comment]
Thanks for update. There's a large PR around tests coming up. I wonder if that fixes the issues:
https://github.com/exo-digital-labs/ERC721R/pull/15
