### ISSUE TITLE
Question: Why do we need notContract() modifier?

### ISSUE THREAD

**Issue by v0xat** [exo-digital-labs/ERC721R#22]
Hi!

Could you please help me understand why in this contract we need to check that `publicSale` and `preSale` are not called by the contracts? Is it to prevent some kind of attack?

Also, after a bit research, I found out that the `isContract` function from the OZ package does not guarantee that the address is not a contract and shouldn't be used for that purpose.

Related links:
- https://github.com/exo-digital-labs/ERC721R/blob/main/contracts/ERC721RExample.sol#L29
- https://docs.openzeppelin.com/contracts/4.x/api/utils#Address-isContract-address-
- https://forum.openzeppelin.com/t/how-to-write-an-onlynoncontract-modifier-function-cant-be-called-by-a-contract/3042/4

**Comment by elie222** [comment]
Thanks. It definitely shouldn't be used on presale. But we're removing it from public sale regardless. 

The intention was prevent certain attacks on the mint as refundable mints will be especially interesting to bots.

Thanks for the OZ link. If you'd like to open an issue to remove notContract you're welcome to but should happen soon regardless
