### ISSUE TITLE
Make this an EIP

### ISSUE THREAD

**Issue by Pandapip1** [exo-digital-labs/ERC721R#37]
This interface would be useful as a standard. I propose writing an EIP and submitting it to the EIPs repository at https://github.com/ethereum/EIPs.

If you don't want to do it, I might :)

**Comment by elie222** [comment]
> This interface would be useful as a standard. I propose writing an EIP and submitting it to the EIPs repository at [ethereum/EIPs](https://github.com/ethereum/EIPs).
> 
> If you don't want to do it, I might :)

Sure. Would be great. This was the interface we used for CFA btw:
https://github.com/exo-digital-labs/ERC721R/blob/main/contracts/cryptofighters/IERC721R.sol

Happy to help around an official EIP as well.

**Comment by Pandapip1** [comment]
Would you be okay if I released the interface (and/or a modification of it) under [CC0](https://eips.ethereum.org/LICENSE)?

**Comment by elie222** [comment]
> Would you be okay if I released the interface (and/or a modification of it) under [CC0](https://eips.ethereum.org/LICENSE)?

Yes, I'm fine with that

**Comment by Pandapip1** [comment]
See https://eips.ethereum.org/EIPS/eip-5507. All discussions should be moved to https://ethereum-magicians.org/t/eip-5507-refundable-nfts/10451.
